name: Deploy Bicep file

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true # Enable Azure PowerShell session

    - name: Install Bicep CLI
      uses: azure/setup-bicep@v1

    - name: Build Bicep file
      run: bicep build InfrastructureAsCode/main.bicep

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Use GitHub Secret
        resourceGroupName: ${{ secrets.AZURE_RG }} # Use GitHub Secret
        template: InfrastructureAsCode/main.json
        parameters: storagePrefix=sample

