name: Deploy Bicep file

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true # Enable Azure PowerShell session

    - name: Bicep Build
      uses: Azure/bicep-build-action@v1.0.0
      with:
          bicepFilePath: ./InfrastructureAsCode/main.bicep
          outputFilePath: azuredeploy.json

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Use GitHub Secret
        resourceGroupName: ${{ secrets.AZURE_RG }} # Use GitHub Secret
        template: ./InfrastructureAsCode/main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false

